const CODE_OK = 200;
const CODE_CREATED = 201;
const CODE_NO_CONTENT = 204;

const CODE_BAD_REQUEST = 400;
const CODE_NOT_FOUND = 404;

module.exports = {
  CODE_OK,
  CODE_CREATED,
  CODE_NO_CONTENT,
  CODE_BAD_REQUEST,
  CODE_NOT_FOUND
}